version: "3.3"
services:

  # PHP service
  app:
    build: .
    container_name: php-app-1
    working_dir: /var/www/teste-vaga-dev/
    volumes:
      - ./:/var/www/teste-vaga-dev
    networks:
      - app-network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db-1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data1:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx-1
    ports:
      - 80:80
    volumes:
      - ./:/var/www/teste-vaga-dev
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data1: